package com.resumeai.domain.enums;

public enum ApplicationEventType {
    APPLIED,
    STAGE_CHANGED,
    NOTE_ADDED,
    SCREENING_COMPLETED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    INTERVIEW_CANCELLED,
    FEEDBACK_SUBMITTED,
    OFFER_CREATED,
    OFFER_APPROVED,
    OFFER_REVISED,
    OFFER_EXTENDED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    REJECTED,
    REOPENED,
    HIRED,
    WITHDRAWN
}
