package com.resumeai.domain.enums;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_STATUS_CHANGED,
    NEW_APPLICATION,
    SCREENING_COMPLETED,
    JOB_SUBMITTED,
    JOB_APPROVED,
    JOB_REJECTED,
    INTERVIEW_ASSIGNED,
    FEEDBACK_DUE,
    OFFER_APPROVAL_NEEDED,
    OFFER_DECISION,
    PIPELINE,
    INVITATION,
    ACCOUNT,
    SYSTEM
}
